apiVersion: v1
kind: Pod

spec:
  serviceAccountName: default

  containers:
    - name: python
      image: python:3.11
      command:
        - cat
      tty: true

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - sleep
    args:
	- "999999"
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
